### PR TITLE
added bssid fetch

### PR DESCRIPTION
**Pull request by wifijanitor**
script to pull the bssid from dashboard

### CODE REVIEW

**Review by TKIPisalegacycipher — CHANGES_REQUESTED** [review]
Thank you @wifijanitor ! This looks great but the preferred credentials approach is using an environment variable -- this is doc'd in the project readme. 

Since the DashboardAPI class will auto-use the key from ENV (if present), you can simply remove the creds lines here and remove API_KEY--you won't need it here and the method would still work.

**Comment by wifijanitor** [comment]
is it ok if I leave the API_KEY in there, but change it to os.getenv()?

**Comment by TKIPisalegacycipher** [comment]
It's not necessary because that happens automatically as a feature of our Python library.

`dashboard = meraki.DashboardAPI()`

will work as-is as long as the variable is set in the environment. Did you need it for some other reason?

**Comment by wifijanitor** [comment]
no, just how I was used to working with it.

removed the API_KEY references, and it works just checking the env var

**Review by TKIPisalegacycipher — APPROVED** [review]
Looking good!

**Pull request merged**
